# Generated by Django 4.1.7 on 2023-03-20 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_pets_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('datetime', models.DateTimeField(default=None)),
                ('ordstatus', models.CharField(max_length=100)),
                ('is_complete', models.BooleanField(default=False)),
                ('ordernum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.pets')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
