# Generated by Django 4.1.7 on 2023-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderof'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusorder', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Статус Заказа',
                'verbose_name_plural': 'Статус Заказов',
            },
        ),
    ]
